---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname nzbget
  namespace: flux-system
spec:
  targetNamespace: downloader
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/downloader/nzbget/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
    - name: generic-device-plugin
  postBuild:
    substitute:
      APP: *appname
