---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nzbget
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nzbget-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: IPVanish
        property: OPENVPN_USER
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: IPVanish
        property: OPENVPN_PASSWORD
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: IPVanish
        property: SERVER_COUNTRIES
    - secretKey: DNS_KEEP_NAMESERVER
      remoteRef:
        key: IPVanish
        property: DNS_KEEP_NAMESERVER
    - secretKey: DOT
      remoteRef:
        key: IPVanish
        property: DOT
