---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./error-pages.yaml
  - ./ingressclass-external.yaml
  - ./service-external.yaml
  # Middlewares will be added after Traefik CRDs are installed
  # - ./middlewares.yaml
